import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import NavbarCustom from "@/screens/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const scrollToSection = (id: string) => {
    const element = document.getElementById(id);
    if (element) {
      setTimeout(() => element.scrollIntoView({ behavior: "smooth" }), 100);
    }
  };
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarCustom />
        {children}
      </body>
    </html>
  );
}
